from flask import Blueprint, render_template
documents_bp=Blueprint("documents",__name__)
@documents_bp.route("/quotation")
def quotation(): return render_template("documents/quotation.html")
@documents_bp.route("/proforma")
def proforma(): return render_template("documents/proforma.html")
@documents_bp.route("/invoice")
def invoice(): return render_template("documents/invoice.html")
@documents_bp.route("/invoice/preview")
def invoice_preview(): return render_template("invoice/professional_invoice.html")
@documents_bp.route("/delivery-challan")
def delivery_challan(): return render_template("documents/delivery_challan.html")
@documents_bp.route("/receipts")
def receipts(): return render_template("documents/receipts.html")
@documents_bp.route("/credit-note")
def credit_note(): return render_template("documents/credit_note.html")
