from flask import Blueprint, render_template
superadmin_bp=Blueprint("superadmin",__name__)
@superadmin_bp.route("/superadmin/clients")
def clients(): return render_template("superadmin/clients.html")
@superadmin_bp.route("/superadmin/plans")
def plans(): return render_template("superadmin/plans.html")
@superadmin_bp.route("/superadmin/updates")
def updates(): return render_template("superadmin/updates.html")
@superadmin_bp.route("/client-data")
def client_data(): return render_template("superadmin/client_data.html")
@superadmin_bp.route("/subscription")
def subscription(): return render_template("superadmin/subscription.html")
@superadmin_bp.route("/audit")
def audit(): return render_template("superadmin/audit.html")
