from flask import Blueprint, render_template
client_bp=Blueprint("client",__name__)
@client_bp.route("/company-profile")
def company_profile(): return render_template("client/company_profile.html")
@client_bp.route("/branches")
def branches(): return render_template("client/branches.html")
@client_bp.route("/users")
def users(): return render_template("client/users.html")
@client_bp.route("/change-password")
def change_password(): return render_template("client/change_password.html")
@client_bp.route("/communication")
def communication(): return render_template("client/communication.html")
